name: Docker Image
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      dockerhub_username:
        required: true
      dockerhub_token:
        required: true
      repo_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo version
        run: |
          echo "Version is ${{ inputs.version }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/scraperr:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/scraperr:${{ inputs.version }}

      - name: Build and push api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/api/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/scraperr_api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/scraperr_api:${{ inputs.version }}

  push-helm-chart:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v4

      - name: Push Helm Chart
        uses: ./.github/actions/push-to-helm
        with:
          app-repo-token: ${{ secrets.GPAT_TOKEN }}

  success-message:
    runs-on: ubuntu-latest
    needs:
      - build
      - push-helm-chart
    steps:
      - name: Send Discord Message
        uses: jaypyles/discord-webhook-action@v1.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: "Scraperr Successfully Built Docker Images"
          username: "Scraperr CI"
          embed-title: "✅ Deployment Status"
          embed-description: "Scraperr successfully built docker images."
          embed-color: 3066993 # Green
          embed-footer-text: "Scraperr CI"
          embed-timestamp: ${{ github.event.head_commit.timestamp }}
